pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)-$(Build.SourceBranchName)

stages:
- stage: build

  jobs:
  - job: buildFront
    steps:
    - script: |
        curl https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_1.23.0-18.1.pre-beta.tar.xz --output flutter.tar.xz
        tar -xf flutter.tar.xz
        flutter/bin/flutter config --enable-web
        flutter/bin/flutter pub get
        flutter/bin/flutter build web
        cp -r build/web/ deploy/web/
        
    - publish: deploy
      artifact: front-pack
- stage: dockerImage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: dockerBuild
    steps:
    - download: current
      artifact: front-pack
      displayName: Download front-pack
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/realityfatality-dcr-front'
        command: 'buildAndPush'
        Dockerfile: '$(Pipeline.Workspace)/front-pack/Dockerfile'
        buildContext: '$(Pipeline.Workspace)/front-pack'
        tags: |
          $(Build.BuildId)
          latest
- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - deployment: DeployFront
      displayName: Deploy front
      pool:
        vmImage: 'Ubuntu-16.04'
      environment: 'production'
      strategy:
        runOnce:
          on:
            failure:
              steps:
                - download: none
                - task: SSH@0
                  inputs:
                    sshEndpoint: 'swarm manager'
                    runOptions: 'commands'
                    commands: 'docker service rollback realityfatality-dcr_front'
                    readyTimeout: '20000'
          deploy:
            steps:
              - download: none
              - task: SSH@0
                inputs:
                  sshEndpoint: 'swarm manager'
                  runOptions: 'commands'
                  commands: 'docker service update --image rtuitlab/realityfatality-dcr-front:$(Build.BuildId) realityfatality-dcr_front'
                  readyTimeout: '20000'