pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)-$(Build.SourceBranchName)

stages:
- stage: build

  jobs:
  - job: buildFront
    steps:


    - task: install-flutter-sdk@0
      inputs:
        channel: 'beta'
    - task: FlutterBuild@0
      inputs:
        target: 'web'
        projectDirectory: '.'
    - publish: build/web
      artifact: front-pack
